# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_name', models.CharField(blank=True, max_length=50, verbose_name='* W_NAME')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(blank=True, default=0, max_length=5)),
                ('time', models.CharField(blank=True, max_length=100)),
                ('close', models.CharField(blank=True, default=0, max_length=5)),
                ('hidden', models.CharField(blank=True, default=0, max_length=5)),
                ('msg_count', models.CharField(blank=True, default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ChatList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('img', models.TextField(blank=True)),
                ('time', models.CharField(blank=True, max_length=50)),
                ('m_type', models.CharField(default='1', max_length=2)),
                ('unread', models.SmallIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('W_NAME', models.CharField(blank=True, max_length=50, verbose_name='* W_NAME')),
            ],
        ),
        migrations.CreateModel(
            name='Give',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_name', models.CharField(blank=True, max_length=50, verbose_name='* W_NAME')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_name', models.CharField(blank=True, max_length=50, verbose_name='* W_NAME')),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_name', models.CharField(blank=True, max_length=50, verbose_name='* W_NAME')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_name', models.CharField(blank=True, max_length=50, verbose_name='* W_NAME')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_not', models.CharField(default='0', max_length=2)),
                ('content', models.TextField(blank=True)),
                ('img', models.TextField(blank=True)),
                ('s_time', models.CharField(blank=True, max_length=50)),
                ('r_time', models.CharField(blank=True, max_length=50)),
                ('s_del', models.CharField(blank=True, max_length=20)),
                ('r_del', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_name', models.CharField(blank=True, max_length=50, verbose_name='* W_NAME')),
                ('username', models.CharField(blank=True, max_length=50, verbose_name='')),
                ('password', models.CharField(blank=True, max_length=50, verbose_name='')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='')),
                ('sex', models.CharField(blank=True, choices=[('0', '\u5973'), ('1', '\u7537'), ('2', '\u5176\u4ed6')], default='2', max_length=10, verbose_name='* \u6027\u522b /Sex')),
                ('age', models.CharField(blank=True, choices=[('1', '12~18'), ('2', '18~25'), ('3', '25~32'), ('4', '33~40'), ('5', '40\u4ee5\u4e0a')], default='2', max_length=10, verbose_name='* \u5e74\u9f84 /Age')),
                ('xingzuo', models.CharField(blank=True, max_length=50, verbose_name='\u661f\u5ea7')),
                ('like', models.CharField(blank=True, max_length=50, verbose_name='')),
                ('score_today', models.CharField(blank=True, max_length=50, verbose_name='')),
                ('score_forever', models.CharField(blank=True, max_length=50, verbose_name='')),
                ('score_sum', models.CharField(blank=True, max_length=50, verbose_name='')),
                ('coin', models.CharField(blank=True, max_length=50, verbose_name='')),
                ('online', models.CharField(blank=True, max_length=50, verbose_name='')),
                ('state', models.CharField(blank=True, max_length=50, verbose_name='')),
                ('time_login_today', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='')),
                ('industry', models.CharField(blank=True, max_length=50, verbose_name='')),
                ('introduction', models.TextField()),
                ('image_url', models.TextField(blank=True)),
                ('gift', models.TextField(blank=True)),
                ('image1', models.FileField(blank=True, upload_to='fig/')),
            ],
        ),
        migrations.CreateModel(
            name='UserImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgData', models.TextField(blank=True)),
                ('time', models.CharField(blank=True, max_length=100)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uid_img', to='chat.User')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='rid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rid_message', to='chat.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='sid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sid_message', to='chat.User'),
        ),
        migrations.AddField(
            model_name='chatlist',
            name='rid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rid_chat_list', to='chat.User'),
        ),
        migrations.AddField(
            model_name='chatlist',
            name='sid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_sid_chat_list', to='chat.User'),
        ),
        migrations.AddField(
            model_name='chat',
            name='rid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rid', to='chat.User'),
        ),
        migrations.AddField(
            model_name='chat',
            name='sid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sid', to='chat.User'),
        ),
        migrations.AddField(
            model_name='block',
            name='b_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buid', to='chat.User'),
        ),
        migrations.AddField(
            model_name='block',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uid', to='chat.User'),
        ),
    ]
