# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, default='1', max_length=50, verbose_name=''),
        ),
    ]
