# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20171007_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.CharField(blank=True, max_length=200, verbose_name=''),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, default='1', max_length=200, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='coin',
            field=models.CharField(blank=True, default='0', max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='online',
            field=models.CharField(blank=True, default='1', max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='score_forever',
            field=models.CharField(blank=True, default='10', max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='score_sum',
            field=models.CharField(blank=True, default='10', max_length=50, verbose_name=''),
        ),
    ]
